#   Hamer CS:GO Hacks configuration instructions:
#
#   - To enable a cheat, simply write true next to it (i.e: glow: true)
#   - To disable a cheat, simply write false next to it (i.e: glow: false)
#   - To change a key, simply write key name next to it (i.e: aim_key: f6)
#
#   The configurations currently written in this file are recommended. You can make changes according to your request.

aimlock: true # turns on aimlock
<<<<<<< Updated upstream
aim_key: ctrl # aimlock key 
aim_fov: 3 # aimlock fov (recommended: 3) 
aim_force_shoot: false # aimlock force shoot
aim_type: head # Where to aim (values: body, random, legit, head - recommended: head)
aim_lock_type: silent # Aim lock type (values: silent, silentrcs, lock - recommended: silent)
=======
aim_key: ctrl # aimlock key 
aim_fov: 3 # aimlock fov (recommended: 3) 
aim_force_shoot: false # aimlock force shoot
aim_type: head # Where to aim (values: body, random, legit, head - recommended: head)
aim_lock_type: silent # Aim lock type (values: silent, silentrcs, lock - recommended: silent)
>>>>>>> Stashed changes

bhop: true # turns on bunny hop
bunny_key: space # bunny hop key

glow: true # turns on glow hack
ct_glow: # glow hack ct colors
    red: 0.0
    green: 0.0
    blue: 2.0 # ct color is blue (recommended)
    opacity: 2.0
t_glow: # glow hack t colors
    red: 2.0 # t color is red (recommended)
    green: 0.0
    blue: 0.0 
    opacity: 2.0

charm: true # turns on charm hack
ct_charm: # charm hack ct colors
    red: 0
    green: 255 # ct color is green (recommended)
    blue: 30
t_charm: # charm hack t colors
    red: 0
    green: 255 # t color is green (recommended)
    blue: 30

fov: true # turns on fov hack
default_fov: 120 # default fov (recommended: 120, default: 90)
noflash: true # disables flash bombs
radar: true # shows enemies in radar

trigger: true # turns on trigger  bot
trigger_delay: 0.1 # trigger bot delay
trigger_key: shift # trigger bot key

recoil: true # turns on recoil helper

rank_checker_key: f6 # rank checker key
